# Project 3

In this project, you will perform a logistic regression on the admissions data we've been working with in projects 1 and 2.

In [30]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import pylab as pl
import numpy as np
import sklearn 

In [5]:
df_raw = pd.read_csv("../assets/admissions.csv")
df = df_raw.dropna() 
print df.head()

   admit    gre   gpa  prestige
0      0  380.0  3.61       3.0
1      1  660.0  3.67       3.0
2      1  800.0  4.00       1.0
3      1  640.0  3.19       4.0
4      0  520.0  2.93       4.0


## Part 1. Frequency Tables

#### 1. Let's create a frequency table of our variables

In [23]:
# frequency table for prestige and whether or not someone was admitted

prestigeAndAdmit = df.groupby(["admit","prestige"])

In [61]:
dfcross = pd.crosstab(df.prestige,df.admit)
dfcross

admit      0   1
prestige        
1.0       28  33
2.0       95  53
3.0       93  28
4.0       55  12

In [32]:
# describe the grouped data

prestigeAndAdmit.describe().unstack()

gpa                                                         \
               count      mean       std   min     25%    50%     75%   max   
admit prestige                                                                
0     1.0       28.0  3.345714  0.375445  2.55  3.1350  3.280  3.5775  4.00   
      2.0       95.0  3.325895  0.376339  2.42  3.0700  3.350  3.5850  4.00   
      3.0       93.0  3.402258  0.379434  2.56  3.1400  3.400  3.6900  4.00   
      4.0       55.0  3.291455  0.369767  2.26  3.0500  3.310  3.4750  4.00   
1     1.0       33.0  3.544242  0.385511  2.42  3.3700  3.610  3.8100  4.00   
      2.0       53.0  3.441698  0.365054  2.62  3.1700  3.450  3.7500  4.00   
      3.0       28.0  3.534643  0.399244  2.65  3.3425  3.620  3.8625  4.00   
      4.0       12.0  3.441667  0.297286  2.86  3.2200  3.535  3.6625  3.74   

                 gre                                                      \
               count        mean         std    min    25%    50%    75%   
admit prestige                                                             
0     1.0       28.0  582.857143  126.574737  340.0  510.0  580.0  685.0   
      2.0       95.0  588.000000  103.323495  380.0  520.0  580.0  660.0   
      3.0       93.0  562.365591  124.650798  220.0  500.0  560.0  640.0   
      4.0       55.0  562.909091  116.327646  300.0  500.0  560.0  630.0   
1     1.0       33.0  636.363636  110.618098  460.0  540.0  620.0  720.0   
      2.0       53.0  612.075472  113.635018  300.0  540.0  620.0  680.0   
      3.0       28.0  616.428571   99.785484  460.0  535.0  620.0  680.0   
      4.0       12.0  603.333333  114.680056  400.0  520.0  610.0  685.0   

                       
                  max  
admit prestige         
0     1.0       800.0  
      2.0       800.0  
      3.0       800.0  
      4.0       800.0  
1     1.0       800.0  
      2.0       800.0  
      3.0       800.0  
      4.0       780.0

## Part 2. Return of dummy variables

#### 2.1 Create class or dummy variables for prestige 

In [46]:
dummy_ranks = pd.get_dummies(df['prestige'],prefix = 'prestige')

dummy_ranks.head(10)

prestige_1.0  prestige_2.0  prestige_3.0  prestige_4.0
0             0             0             1             0
1             0             0             1             0
2             1             0             0             0
3             0             0             0             1
4             0             0             0             1
5             0             1             0             0
6             1             0             0             0
7             0             1             0             0
8             0             0             1             0
9             0             1             0             0

#### 2.2 When modeling our class variables, how many do we need? 



Answer: 

## Part 3. Hand calculating odds ratios

Develop your intuition about expected outcomes by hand calculating odds ratios.

In [44]:
# Use cross validation to train and predict on specific parts of the 

In [47]:
cols_to_keep = ['admit', 'gre', 'gpa']
handCalc = df[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_1':])
print handCalc.head()

   admit    gre   gpa  prestige_1.0  prestige_2.0  prestige_3.0  prestige_4.0
0      0  380.0  3.61             0             0             1             0
1      1  660.0  3.67             0             0             1             0
2      1  800.0  4.00             1             0             0             0
3      1  640.0  3.19             0             0             0             1
4      0  520.0  2.93             0             0             0             1


In [48]:
#crosstab prestige 1 admission 
#crosstab is basically like pivot table
# frequency table cutting prestige and whether or not someone was admitted

print pd.crosstab(handCalc['admit'], handCalc['prestige_1.0'], rownames= ['admit'])

prestige_1.0    0   1
admit                
0             243  28
1              93  33


#### 3.1 Use the cross tab above to calculate the odds of being admitted to grad school if you attended a #1 ranked college

In [58]:
df.dtypes

castType = df.prestige.astype('int64')

In [ ]:
odds_admittance = 

#### 3.2 Now calculate the odds of admission if you did not attend a #1 ranked college

#### 3.3 Calculate the odds ratio

#### 3.4 Write this finding in a sentenance: 

Answer: 

#### 3.5 Print the cross tab for prestige_4

#### 3.6 Calculate the OR 

#### 3.7 Write this finding in a sentence

Answer:

## Part 4. Analysis

In [ ]:
# create a clean data frame for the regression
cols_to_keep = ['admit', 'gre', 'gpa']
data = df[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_2':])
print data.head()

We're going to add a constant term for our Logistic Regression. The statsmodels function we're going to be using requires that intercepts/constants are specified explicitly.

In [ ]:
# manually add the intercept
data['intercept'] = 1.0

#### 4.1 Set the covariates to a variable called train_cols

#### 4.2 Fit the model

#### 4.3 Print the summary results

#### 4.4 Calculate the odds ratios of the coeffiencents and their 95% CI intervals

hint 1: np.exp(X)

hint 2: conf['OR'] = params
        
           conf.columns = ['2.5%', '97.5%', 'OR']

#### 4.5 Interpret the OR of Prestige_2

Answer: 

#### 4.6 Interpret the OR of GPA

Answer: 

## Part 5: Predicted probablities


As a way of evaluating our classifier, we're going to recreate the dataset with every logical combination of input values. This will allow us to see how the predicted probability of admission increases/decreases across different variables. First we're going to generate the combinations using a helper function called cartesian (above).

We're going to use np.linspace to create a range of values for "gre" and "gpa". This creates a range of linearly spaced values from a specified min and maximum value--in our case just the min/max observed values.

In [ ]:
def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.
    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.
    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.
    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])
    """

    arrays = [np.asarray(x) for x in arrays]
    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = n / arrays[0].size
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in xrange(1, arrays[0].size):
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out

In [ ]:
# instead of generating all possible values of GRE and GPA, we're going
# to use an evenly spaced range of 10 values from the min to the max 
gres = np.linspace(data['gre'].min(), data['gre'].max(), 10)
print gres
# array([ 220.        ,  284.44444444,  348.88888889,  413.33333333,
#         477.77777778,  542.22222222,  606.66666667,  671.11111111,
#         735.55555556,  800.        ])
gpas = np.linspace(data['gpa'].min(), data['gpa'].max(), 10)
print gpas
# array([ 2.26      ,  2.45333333,  2.64666667,  2.84      ,  3.03333333,
#         3.22666667,  3.42      ,  3.61333333,  3.80666667,  4.        ])


# enumerate all possibilities
combos = pd.DataFrame(cartesian([gres, gpas, [1, 2, 3, 4], [1.]]))

#### 5.1 Recreate the dummy variables

In [ ]:
# recreate the dummy variables

# keep only what we need for making predictions


#### 5.2 Make predictions on the enumerated dataset

#### 5.3 Interpret findings for the last 4 observations

Answer: 

## Bonus

Plot the probability of being admitted into graduate school, stratified by GPA and GRE score.